import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/blog-components/Navbar";
import Footer from "@/components/blog-components/Footer";

const manRope = Manrope({
    variable: "--font-manRope",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={` ${manRope.variable} antialiased`}>
                <div className="bg-(--primary) text-(--warm-black) min-h-screen selection:bg-(--accent) selection:text-white">
                    <Navbar />
                    {children}
                </div>
                <Footer />
            </body>
        </html>
    );
}
